apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 386771388804.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 386771388804.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
